language: go

go:
  - 1.8
  - 1.7
  - master

env:
  # The "plugin" package required the collectd sources, which are not (yet) available.
  - CGO_ENABLED=0

go_import_path: collectd.org

matrix:
  allow_failures:
    - go: master

before_script:
  - go get github.com/golang/lint/golint

script:
  - go vet -x ./...
  - go test -v ./...

# TODO(octo): run the fuzz test:
# - go test -v -tags gofuzz ./...
